### ISSUE TITLE
Switch Ethereum Minting from Ganache to Devnet

### ISSUE THREAD

**Issue by lukaswolfrum** [amosproj/amos2022ss07-nft-playbook#100]
## User story
1. As a power user
2. I want / need a well tested environment
3. So that the programm runs smoothly

## Acceptance criteria
* Minting on Ethereum Online  Devnet is possbile
* no dependecy on Ganache left

## Definition of done (DoD)
* A Feature is Done when all its Acceptance criterias are fulfilled
* A Feauture is Done when the code has been peer reviewed from the dedicated team
* A Feature is Done when it has been tested
* A Feature is Done when its core functionality has been commented properly
* A Feature is Done when it can be fully integrated into the main branch without negative side effect
* A Feature is Done when its core functionality has been documented properly

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by MPSebastian** [comment]
We (@phildree, @schlingling) created a new Metamask Account for testing purposes only!

We also got some test ETH, so we can deploy contracts and mint our nfts on Ethereum.
For this we used faucet: https://faucet.metamask.io/

After selecting the corresponding test-network you can verifiy your deployment and minting on etherscan: https://etherscan.io/
