### ISSUE TITLE
Show progress when work in progress

### ISSUE THREAD

**Issue by lukaswolfrum** [amosproj/amos2022ss07-nft-playbook#139]
## User story
1. As a power user
2. I want / need to be aware about the status of the program
3. So that I don't kill the program 

## Acceptance criteria
* Showing the user some sort progress or at least feedback that the program is working in progress
* deploying a contract, minting, uploading to pinata
* Bulk minting show 0/3 at the beginning for progress

## Definition of done (DoD)
* A Feature is Done when all its Acceptance criterias are fulfilled
* A Feauture is Done when the code has been peer reviewed from the dedicated team
* A Feature is Done when it has been tested
* A Feature is Done when its core functionality has been commented properly
* A Feature is Done when it can be fully integrated into the main branch without negative side effect
* A Feature is Done when its core functionality has been documented properly

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by phildree** [comment]
Info for asynchronous execution using multithreading: https://nodejs.org/api/worker_threads.html
