### ISSUE TITLE
Submit Demo Day Video

### ISSUE THREAD

**Issue by Noah-Kurz** [amosproj/amos2022ss07-nft-playbook#148]
Requirements:
- This video can be used as inspiration https://www.youtube.com/watch?v=EbzdV058sfI
- Should have one slide about Requirements
- Should have one slide about Architecture
- Should have a Demo Part
- All in all 3 Minutes long
- 30 secs Requirements
-  30 secs Architecture
- 1:50 Minutes Demo
- 10 Sec outro

Plan:

- [x] POs Make requirement Slide and Text
- [x] DEVs make text and slide for architecture @schlingling 
- [x] DEVs make Demo concept and text @laila-rin @lukas-rotsching 
- [x] POs Make outro Slide and Text
- [x] We allign all parts in regard to design ASAP, POs coordinate
- [x] All 3 parts are recorded seperatly
- [x] Someone with good video editing skills puts all together

General info demo day: [https://github.com/dirkriehle/amos-course/blob/main/Generated/Lecture slides/AMOS H01 - Demo Day Preparation.pdf](url)

**Comment by schlingling** [comment]
@lukaswolfrum @laila-rin @Noah-Kurz @lukas-rotsching 
Mein Part (Architecture) ist fertig. Hier eine kurze Anleitung für euch:
Habe in Google-Drive einen neuen Folder Sprint 12 angelegt, hier sind 2 PPTs drinnen (Siehe Screenshot). Nr1 ist die finale Version der Folien. Kopiert euch einfach aus Nr2. die Slide-Vorlagen in den entsprechenden Abschnitt in der Nr.1 rein.

Achtung: Lokal mit nativem PowerPoint-Client arbeiten, da es sonst die Vorlage zerschiesst (Ich habe mir einfach Google Drive runtergeladen und den Ordner gesynct, dann kann ich direkt mit PPT die Folien öffnen und nicht mit GoogleSlides).

Wenn ihr noch Icons braucht, dann findet ihr welche in der VORLAGE in den letzten paar Folien.

@lukas-rotsching : Das Frontend konnte ich jetzt noch nicht modellieren, hier wäre es gut, wenn mir jemand vom CLI-Team Input gibt.
