### ISSUE TITLE
Research "Add Wallet" feature 

### ISSUE THREAD

**Issue by Noah-Kurz** [amosproj/amos2022ss07-nft-playbook#29]
## User story
1. As a poweruser
2. I want / need to connect a new wallet like Metamask to the CLI
3. So that I can pay gas fees for the minting process and don't have to enter my information everytime

*Side note from Noah: Maybe using "cold wallets" would make your life easier?*

*Side node Lukas W: Ledger Nano X e.g. can hold ETH, MATIC, SOL and FLOW*

*further side note Lukas W: I found this https://zabo.com/, https://developers.cryptoapis.io/technical-documentation/general-information/overview maybe this is helpful?*

## Acceptance criteria
* The wallet should be able to hold as many coins from different chains as possible, in particular : Polygon / ETH, Flow, Solana
* The Wallet should be easily connectable to the CLI tool
* The Wallet should have a good reputation and be open source / decentralized
* The Wallet should be secure (no known security issues)
* Maybe several wallets are needed to hold the gas fees for the needed chains Polygon / ETH, Flow, Solana

## Definition of done (DoD)
* A Feature is Done when all its Acceptance criterias are fulfilled
* A Feautre is Done when the code has been peer reviewed
* A Feature is Done when it has been tested at least 3 times
* A Feature is Done when its core functionality has been commented properly

## Definition of done (DoD)
* A Feature is Done when all its Acceptance criterias are fulfilled
* A Feauture is Done when the code has been peer reviewed from the dedicated team
* A Feature is Done when it has been tested
* A Feature is Done when its core functionality has been commented properly
* A Feature is Done when it can be fully integrated into the main branch without negative side effect

**Comment by MPSebastian** [comment]
Result for Wallet research: 

- Alle Wallets sind Browser Extensions -> Funktioniert nur mit Website

- Cold Wallets ??? (nicht so sinnvoll) (OpenSource)

----> Einfach Private Keys & nochmal nachfragen!!!
