### ISSUE TITLE
Submit Organizationals Sprint05

### ISSUE THREAD

**Issue by Noah-Kurz** [amosproj/amos2022ss07-nft-playbook#53]
## Acceptance criteria:

Submit organisationals / homework

- [x]  Feature board @ POs
- [x]  Planning documents @ POs
- [x] Tag sprint release candidate @ Releasemanager
- [x] Release Plan @ POs
- [x] Build process video @ Releasemanager
- [x] Upload process video @ Releasemanager

**Comment by schlingling** [comment]
@lukaswolfrum @Noah-Kurz 
Can you keep an eye on @dikovh Feedback mail for sprint4, that we can focus on the suggestion for improvement next meeting? Thank you guys!
