### ISSUE TITLE
Test Environment / Seperating Frontend and Backend

### ISSUE THREAD

**Issue by Noah-Kurz** [amosproj/amos2022ss07-nft-playbook#55]
## User story
1. As a poweruser
2. I want / need seperated frontend and backend
3. So that it is modular and good for further developments

## Acceptance criteria
* test environment should be used 
* setup of the repository in monorepository
* seperating Frontend and Backend

## Definition of done (DoD)
* A Feature is Done when all its Acceptance criterias are fulfilled
* A Feauture is Done when the code has been peer reviewed from the dedicated team
* A Feature is Done when it has been tested
* A Feature is Done when its core functionality has been commented properly
* A Feature is Done when it can be fully integrated into the main branch without negative side effect

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by schlingling** [comment]
@phildree Can you have a look to following errormessage which occurs after our refactoring? It is the same path-problem we solved two weeks ago really quick.

![image](https://user-images.githubusercontent.com/58326464/170538844-e8cfd9af-b5db-4292-b73e-bc0979603783.png)

**Comment by MPSebastian** [comment]
I fixed the path problem in the solidity file. The program can be executed properly now! :)
