### ISSUE TITLE
Exception handling Middleware/Backend

### ISSUE THREAD

**Issue by Noah-Kurz** [amosproj/amos2022ss07-nft-playbook#66]
## User story
1. As a poweruser
2. I want / need to be prompted with error messages and other notifications
3. So that he knows how to change input in case of exceptions

## Acceptance criteria
- [x] Implement exception handling CLI
- [x]  Implement exception handling Middleware
- [x] Implement exception handling Backend
- [x] Catch Error when reading Configfile
- [x] Catch Error when Blockchain-Interface wents wrong
- [x] Alles was im Backend fliegt, fängt Middleware ab, wrappt diese und gibt eine generische Exception an CLI weiter
- [x] In Middleware alle awaits auflösen

## Definition of done (DoD)
* A Feature is Done when all its Acceptance criterias are fulfilled
* A Feauture is Done when the code has been peer reviewed from the dedicated team
* A Feature is Done when it has been tested
* A Feature is Done when its core functionality has been commented properly
* A Feature is Done when it can be fully integrated into the main branch without negative side effect

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by phildree** [comment]
Wir haben gestern nochmal kurz über das Thema Exception-Handling gesprochen und herausgefunden, dass man in JS/TS
 noch nicht mal enforcen kann, das Exceptions behandelt werden müssen..
 Das macht's voll nervig im Backend Exceptions zu behandeln, weil man erst ewig tief in alle (abhängigen) APIs gucken muss, was die so schmeißen..
Vom Prinzip her ist aber doch auch nicht nötig im Backend/Middleware Exceptions zu catchen und dann eine neue zu werfen, oder? Können wir nicht einfach nur ganz oben in der CLI Exceptions fangen und entsprechend etwas in die Richtung von "Falsche Eingaben oder verbindungsprobleme => Eingaben und/oder Netzwerk prüfen" Printen?

**Comment by schlingling** [comment]
Supporte den Vorschlag von @phildree. Im Backend/Middleware kein excpetion-handling machen, und bei jedem Call von CLI an die Middleware, mittels try/catch, Fehlerfälle abfangen und entsprechend an den User kommunizieren --> in den meisten fällen dann etwaige State-Changes rückgängig machen und die CLI quasi zurücksetzen.

@lukas-rotsching & @tawfeeka: @phildree und ich wollten jetzt gestern nicht damit anfangen, in euerer CLI das umzusetzen, da ihr ja dann doch gerne dort den Hut aufhabt. Wenn ihr uns das GO gebt, übernehmen wir das selbstverständlich. Wenn nicht, dann bitte wie besprochen umsetzen. Anycase, bitte um Rückmeldung, ob ihr beiden oder Backendteam das machen soll 🤗

**Comment by lukas-rotsching** [comment]
Also wo man Exceptions behandelt kommt halt so drauf an... Ich wollte ja im Frontend eigentlich, falls möglich gar keine awaits auf die Middleware mehr haben. Die sind eigentlich überall sinnlos, weil sie genau so gut einfach vorher aufgelöst werden könnten. try/catch sollte man ja aber auch ohne await nutzen können. Exceptions könnten also durchkommen. Die Frage ist jetzt nur, welche Arten von Exceptions können überhaupt auftreten und sind die fürs Frontend relevant oder gegebenenfalls vom Backend oder der Middleware selbst zu fixen? Ich weiß nicht, welceh Arten von Fehlern überhaupt bei euch auftreten können, weswegen ich mir hier mit einer Beurteilung schwer tue. Ich wüsste aber auch nicht, was die CLI eigentlich tun sollte, wenn ein Fehler im Backend auftritt. Einziger Fehlerfall, der mir so auf die schnelle einfällt, der im Frontend irgendwie relevant wäre, wäre, dass das Netzwerk nicht erreichbar ist oder die config file nicht gelesen werden konnte. Dann möchte ich dem Nutzer vielleicht einfach kurz eine hilfreiche Fehlermeldung geben und sonst aber auch nichts weiter machen. (Bei fehlender config file vielleicht Programm direkt wieder beenden). Das wäre sehr viel schöner umzusetzen, wenn ich nicht in der Frontend alle Fehler behandeln muss, sondern wenn z.B. die Middleware alles abfängt und dann, falls der Fehler im Frontend relevant ist, eine standardisierte Exception mit einer Beschreibung wirft, die ich dem Nutzer einfach direkt so anzeigen kann. Ich wüsste nämlich nicht, wie das Frontend sonst eigentlich bestimmen soll, wo ein Fehler genau herkommt, weil das Frontend ja noch nicht mal weiß, was wir eigentlich alles unterstützen.
Ich weiß nicht, ob das jetzt hier alles verständlich ist. Ich werde dann heute Abend im Meeting einfach nochmal drauf eingehen.
